"""Modelupdated

Revision ID: 3049e479c589
Revises: fa07eddbbdda
Create Date: 2026-08-23 23:01:09.625575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3049e479c589'
down_revision: Union[str, Sequence[str], None] = 'fa07eddbbdda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Profile_doctor_id'), 'Profile', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_Profile_user_id'), 'Profile', ['user_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_profile_id'), 'appointments', ['profile_id'], unique=False)
    op.create_index(op.f('ix_appointments_start_time'), 'appointments', ['start_time'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_profile_id'), 'audit_logs', ['target_profile_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_timestamp'), 'chat_messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_health_reports_uploaded_by'), 'health_reports', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_health_reports_user_id'), 'health_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_medical_analysis_report_id'), 'medical_analysis', ['report_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_medicine_id'), 'prescriptions', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_profile_id'), 'prescriptions', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_profile_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_medicine_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_medical_analysis_report_id'), table_name='medical_analysis')
    op.drop_index(op.f('ix_health_reports_user_id'), table_name='health_reports')
    op.drop_index(op.f('ix_health_reports_uploaded_by'), table_name='health_reports')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_timestamp'), table_name='chat_messages')
    op.drop_index(op.f('ix_audit_logs_target_profile_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_appointments_start_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_profile_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_Profile_user_id'), table_name='Profile')
    op.drop_index(op.f('ix_Profile_doctor_id'), table_name='Profile')
    # ### end Alembic commands ###
