"""initial schema

Revision ID: 5cb2a6953d23
Revises: 46db4309836a
Create Date: 2026-06-25 01:08:52.053811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb2a6953d23'
down_revision: Union[str, Sequence[str], None] = '46db4309836a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Profile', ['id'])
    op.add_column('appointments', sa.Column('typeof', sa.String(), nullable=True))
    op.drop_column('appointments', 'notes')
    op.create_unique_constraint(None, 'auth_users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_users', type_='unique')
    op.add_column('appointments', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('appointments', 'typeof')
    op.drop_constraint(None, 'Profile', type_='unique')
    # ### end Alembic commands ###
