"""newcolumn

Revision ID: 8ba834ef526e
Revises: 370325941b53
Create Date: 2026-07-03 00:52:15.454159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba834ef526e'
down_revision: Union[str, Sequence[str], None] = '370325941b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Profile', ['id'])
    op.create_unique_constraint(None, 'auth_users', ['id'])
    op.add_column('health_reports', sa.Column('analysis_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_reports', 'analysis_status')
    op.drop_constraint(None, 'auth_users', type_='unique')
    op.drop_constraint(None, 'Profile', type_='unique')
    # ### end Alembic commands ###
